apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-cart-deployment
spec:
  selector:
    matchLabels:
      app: cart
  replicas: 1
  template:
    metadata:
     labels:
       app: cart
    spec:
     containers:
     - name: cart
       image: gnishanth444/k8-micro-services:app-cart-0.0.1
       ports:
       - containerPort: 1004
         name: cart

---
apiVersion: v1
kind: Service
metadata:
  name: cart
spec:
  selector:
    app: cart
  ports:
   - port: 1004
     targetPort: 1004
  type: ClusterIP

