apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
     labels:
       app: frontend
    spec:
     containers:
     - name: frontend
       image: gnishanth444/k8-micro-services:frontend-0.0.6
       ports:
       - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
   - port: 8080
     targetPort: 8080
     nodePort: 30009
  type: NodePort
                   
